name: Release version check

on:
  push:
    tags:
      - 'v*'
  release:
    types: [created, published, edited, prereleased, released]

jobs:
  check_versions:

    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Get versions into environment
      run: |
        VERSION=$(python setup.py --version)
        TAG=${GITHUB_REF##*/v}
        echo "setup_version=$VERSION" >> $GITHUB_ENV
        echo "tag_version=$TAG" >> $GITHUB_ENV

    - name: Compare versions and report
      run: |
        echo "setup.py version: ${{ env.setup_version }}"
        echo "Latest tag version: ${{ env.tag_version }}"
        if [[ ${{ env.setup_version }} != ${{ env.tag_version }} ]]; then
          echo "Versions are not identical, quitting workflow..."
          exit 23
        else
          echo "OK, versions match - possibly even create release?"
          exit 0
        fi
