name: Compare setup.py and release tag versions

on:
  push:
    tags:
      - 'v*'
  release:
    types: [created, published]

jobs:
  check_versions:

    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Get versions into environment
      run: |
        VERSION=$(python setup.py --version)
        TAG=${GITHUB_REF##*/v}
        echo "setup_version=$VERSION" >> $GITHUB_ENV
        echo "tag_version=$TAG" >> $GITHUB_ENV

    - name: Compare versions inside environment
      run: |
        echo "setup.py version: ${{ env.setup_version }}"
        echo "Latest tag version: ${{ env.tag_version }}"
        if [[ ${{ env.setup_version }} != ${{ env.tag_version }} ]]; then
          echo "Warn user and quit workflow."
        else
          echo "Continue workflow - possibly even create release?"
        fi

    #${{ github.event.release.tag_name }}"
    ##- uses: oprypin/find-latest-tag@v1
    ##  with:
    ##    repository: discogs_client/rest.js  # The repository to scan.
    ##    releases-only: true  # We know that all relevant tags have a GitHub release for them.
    ##  id: joalla  # The step ID to refer to later.
 
    #- run: echo "Latest release tag is at version ${{ steps.joalla.outputs.tag }}"